services:
  db:
    image: postgres:latest
    container_name: Alan-Tuning-base
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
  back:
    build: ./back-end
    container_name: Alan-Tuning-back
    ports:
      - "80:80"
    volumes:
      - ./back-end:/code:z
    depends_on:
      db:
        condition: service_healthy